# Generated by Django 5.1.4 on 2025-04-23 11:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_alter_review_options_review_is_deleted"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchedmovie",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "permissions": [
                    ("can_block_user", "Может блокировать пользователей"),
                    ("can_delete_review", "Может удалять отзывы"),
                ]
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(
                default=False, help_text="Отмечает пользователя как администратора"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_blocked",
            field=models.BooleanField(
                default=False, help_text="Блокирует доступ пользователя к сайту"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="bio",
            field=models.TextField(
                blank=True, help_text="Биография пользователя", null=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="favorite_genre",
            field=models.ForeignKey(
                blank=True,
                help_text="Любимый жанр пользователя",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="movies.genre",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(
                blank=True,
                help_text="Фото профиля",
                null=True,
                upload_to="profile_photos/",
            ),
        ),
        migrations.AlterField(
            model_name="usergenrepreference",
            name="rating",
            field=models.IntegerField(
                help_text="Оценка жанра от 1 до 10",
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Оценка должна быть не менее 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        10, message="Оценка должна быть не более 10"
                    ),
                ],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usergenrepreference",
            unique_together={("user", "genre")},
        ),
        migrations.DeleteModel(
            name="SavedMovie",
        ),
        migrations.DeleteModel(
            name="WatchedMovie",
        ),
    ]
