# Generated by Django 5.1.4 on 2025-06-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="favorite_genre",
        ),
        migrations.DeleteModel(
            name="UserGenrePreference",
        ),
    ]
