# Generated by Django 5.1.4 on 2025-04-09 12:06

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="actor",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="actor_name_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"],
                name="movie_title_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
