# Generated by Django 5.1.4 on 2025-04-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_favoriteactor"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="trailer_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
