# Generated by Django 5.1.4 on 2025-04-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_movie_trailer_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="trailer_urls",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
