# Generated by Django 5.1.4 on 2025-04-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_movie_trailer_urls"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={"verbose_name": "Отзыв", "verbose_name_plural": "Отзывы"},
        ),
        migrations.AddField(
            model_name="review",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удалён"),
        ),
    ]
